// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnvkeuzdqxgfcdztzmrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZudmtldXpkcXhnZmNkenR6bXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzI5MzcsImV4cCI6MjA2MDc0ODkzN30.iuhg9UqT-u84hqFhgadqZeNCfIrXOofHWc7jZhkkNNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);